### ISSUE TITLE
Binary Block Read

### ISSUE THREAD

**Issue by RUGMJ** [RedstoneTools/redstone-tools#38]
[Discord link](https://discord.com/channels/1071119659346169907/1071203521539620935)

> Reads your selection as a binary number. Your selection must be a 1x1xN, where the first position is the least significant bit.

**Comment by RUGMJ** [comment]
#35 needs to be completed before this as it this uses the world edit selection as an input

**Comment by Matthias1590** [comment]
We should probably name this //read as opposed to /read since it uses worldedit

**Comment by Matthias1590** [comment]
Closed by #57
