### ISSUE TITLE
Core: Configuration System

### ISSUE THREAD

**Issue by orbyfied** [RedstoneTools/redstone-tools#39]
Since there is currently no universal configuration system in place, I would like to implement one.

It would provide universal support for persistent configuration, meaning there is no need to make sure developers follow conventions.
In the future, the aim is to also provide an automatically generated GUI for configuring all options.

The aim is to have something along the lines of:
```java
public class MyFeature extends AbstractFeature {
  @Option
  String a = "default value";
  
  // can be contained in a 
  // seperate class for organization
  static class MyOptions {
    @Option
    // use boxed types to allow null values
    Integer b = 69;
  }

  @Options
  MyOptions options;
}
```

**Comment by orbyfied** [comment]
pls assign me fhis 🙏

**Comment by Matthias1590** [comment]
We wont be working on this until V1 is done
