### ISSUE TITLE
Make /base command report invalid number error

### ISSUE THREAD

**Issue by Matthias1590** [RedstoneTools/redstone-tools#43]
Currently when you provide an invalid number (`/base 10 _2j5 2`, _2j5 is not a valid base 10 number) it'll display a weird error message, it should throw a CommandSyntaxException instead

**Comment by RUGMJ** [comment]
Should be as easy as wrapping everything in a try catch and throwing the exception in the catch block

**Comment by Matthias1590** [comment]
Should be, yeah, do you want to be assigned? @RUGMJ

**Comment by Matthias1590** [comment]
Closed by #58
