### ISSUE TITLE
Update redstone after //paste

### ISSUE THREAD

**Issue by Matthias1590** [RedstoneTools/redstone-tools#60]
Should update all redstone in the WE selection, send any feedback messages using the WE api

**Comment by Matthias1590** [comment]
https://discord.com/channels/1071119659346169907/1071203627181543435

**Comment by MiranCZ** [comment]
Is this supposed to work while the game is frozen? Because redstone updates regularly

**Comment by Matthias1590** [comment]
We don't want a command anymore, we just want to update all redstone that gets pasted after a WE paste

**Comment by MiranCZ** [comment]
I can try to do this

**Comment by MiranCZ** [comment]
This should propably be a gamerule? because I can see this making a lot of lag

**Comment by Matthias1590** [comment]
Yeah we want this to be toggleable so a gamerule should work for now
