### ISSUE TITLE
Commands are not in packages

### ISSUE THREAD

**Issue by MiranCZ** [RedstoneTools/redstone-tools#76]
Title

**Comment by Matthias1590** [comment]
I don't see the issue?

**Comment by Matthias1590** [comment]
They should all be in 1 package, each command is represented by 1 class anyway

**Comment by MiranCZ** [comment]
Yeah, but then you have the abstract classes mixing up with the commands

**Comment by MiranCZ** [comment]
Maybe someone just forgot to move `PickBlockFeature` and `RayCastFeature` outside the packages?

**Comment by Matthias1590** [comment]
I think it's fine to have them like this

**Comment by Matthias1590** [comment]
If this ends up not working we can move the abstract classes somewhere else

**Comment by MiranCZ** [comment]
Why is it like this? `CommandFeature` is outside. And you have those two inside with other actual commands

**Comment by Matthias1590** [comment]
CommandFeature isnt outside?

**Comment by MiranCZ** [comment]
Oh, `AbstractFeature`

**Comment by Matthias1590** [comment]
Yes, that's outside of the commands and toggleable packages because it is neither, its the superclass of all commands

**Comment by MiranCZ** [comment]
And `CommandFeature` isnt superclass of all commands?

**Comment by Matthias1590** [comment]
No, only of command features (not toggleable ones), which is why it's in the commands package
