### ISSUE TITLE
Make /airplace configurable

### ISSUE THREAD

**Issue by MiranCZ** [RedstoneTools/redstone-tools#79]
Make it so that you can configure distance where the block is being placed. I think it would be useful not having only 6 block distance

**Comment by orbyfied** [comment]
Or maybe be able to configure it when you run the /airplace command like /airplace <reach: default = 6>

I am currently working on the airplace feature already so I could implement this

**Comment by Snudget** [comment]
or you could shift+scroll the distance

**Comment by orbyfied** [comment]
Yeah or have like a command `/airplace incrementreach` and allow people to bind it to keys with macros

**Comment by Matthias1590** [comment]
or we just make the player's reach configurable in general, not just for airplace

**Comment by Matthias1590** [comment]
This'll be implemented by #80
