### ISSUE TITLE
QuickTP revise

### ISSUE THREAD

**Issue by DiamondTaco** [RedstoneTools/redstone-tools#85]
From the dev meeting, matt wanted:
- default of 50 blocks
- maximum of some kind

**Comment by DiamondTaco** [comment]
can i get assigned to this?

**Comment by Matthias1590** [comment]
Sure, could you make the maximum default to the render distance?

**Comment by DiamondTaco** [comment]
> Sure, could you make the maximum default to the render distance?

alright

**Comment by DiamondTaco** [comment]
added in #89
