### ISSUE TITLE
Revise Color Code

### ISSUE THREAD

**Issue by DiamondTaco** [RedstoneTools/redstone-tools#92]
Color code:
- Does not detect glass
-  Change onlyWhite argument to onlyColor (instead of only coloring white when onlyWhite is set to true, only color the given color if onlyColor is set)

**Comment by DiamondTaco** [comment]
can i get assigned to this?

**Comment by Matthias1590** [comment]
Could you refactor the colored blocks into some utils class that checks if a block is colored and what color it has?

**Comment by DiamondTaco** [comment]
done in #94
